//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalServices.Paises
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPITALES_PAISES
    {
        public int COD_CAPITAL { get; set; }
        public string NOMBRE_CAPITAL { get; set; }
        public int NUMERO_HABITANTES_CAPITAL { get; set; }
        public string IDIOMA_PREDOMINANTE_CAPITAL { get; set; }
        public int CODIGO_PAIS { get; set; }
    
        public virtual PAISES PAISES { get; set; }
    }
}
